In [11]:
import tensorflow as tf 


Creating simple tensor with matrics

In [17]:
t = tf.constant([[1, 2, 3], [4, 5, 6]])
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [15]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [19]:
# just like an ndarray ,a tf. Tensor has a shape and a data type (dtype)
print(t.shape)
print(t.dtype)


(2, 3)
<dtype: 'int32'>


In [27]:
# indexing works much like in numpy 
#[[1,2,3],
# [4,5,6]]
t[:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6]], dtype=int32)>

In [25]:
t[...,1,tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [5]], dtype=int32)>

In [29]:
# most important , all sorts of tensor operations are available
t+10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [30]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)>

In [ ]:
t@ tf.transpose(t) # perform matrix , transpose swaps the row and colums of the tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [33]:
tf.reduce_mean(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [34]:
t

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

Keras low -level API


In [36]:
from tensorflow import keras 
k= keras.backend

In [40]:
k.square(k.transpose(t))+10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 26],
       [14, 35],
       [19, 46]], dtype=int32)>

Tensors  and numpy 


In [41]:
import numpy as np 


In [42]:
a = np.array([2.,4.,5.])

In [43]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [44]:
t.numpy(
)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [45]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [46]:
np.square(t)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

Type Conversions 

In [50]:
tf.constant(2.)+tf.concat(40)

TypeError: Missing required positional argument

In [53]:
tf.constant(2.) + tf.constant(40., dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2] name: 

In [54]:
tf.constant(4.)+tf.constant(40., dtype=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=44.0>

Variable 

In [56]:
v= tf.Variable([[1,2,3,4],[5,6,7,8]])
v

<tf.Variable 'Variable:0' shape=(2, 4) dtype=int32, numpy=
array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int32)>

In [57]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]], dtype=int32)>

In [58]:
v[0,1].assign(43)

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[ 2, 43,  6,  8],
       [10, 12, 14, 16]], dtype=int32)>

In [63]:
v[:,2].assign([0,2])

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[ 2, 43,  0,  8],
       [10, 12,  2, 16]], dtype=int32)>

In [64]:
v.scatter_nd_update(indices=[[0,0],[1,2]],updates=[100,200])

<tf.Variable 'UnreadVariable' shape=(2, 4) dtype=int32, numpy=
array([[100,  43,   0,   8],
       [ 10,  12, 200,  16]], dtype=int32)>

spare tensors

In [72]:
values = tf.constant([41, 30], dtype=tf.int32)
indices = tf.constant([[1, 2], [3, 3]], dtype=tf.int64)
dense_shape = tf.constant([4, 8], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(indices=indices, values=values, dense_shape=dense_shape)


print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([41 30], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 8], shape=(2,), dtype=int64))


Tensor Array 

In [80]:
value1 = tf.constant(2.)
value2 = tf.constant(3.)
value3 = tf.constant(4.)
tf_array = tf.TensorArray(dtype=tf.float32,size=3)

tf_array=tf_array.write(0,value1)
tf_array= tf_array.write(1,value2)
tf_array=tf_array.write(2,value3)
print(tf_array.read(0))



tf.Tensor(2.0, shape=(), dtype=float32)


Ragged Tensor 

In [82]:
ragged_tensor  = tf.ragged.constant([[1,2],
                                    [1,2,3,4,5,6,7,8,9,22,34,45,33,223,234,556,4555],
                                     [1,2,4]])
ragged_tensor

<tf.RaggedTensor [[1, 2], [1, 2, 3, 4, 5, 6, 7, 8, 9, 22, 34, 45, 33, 223, 234, 556, 4555],
 [1, 2, 4]]>

String Tensors

In [93]:
Tensor_string1 = tf.constant("hello")
Tensor_string2 = tf.constant("manish swami")
print(Tensor_string1)
print(Tensor_string2)
# join the both strings using strings.join method
new_tensor_string = tf.strings.join([Tensor_string1,Tensor_string2],separator=" ")
print(new_tensor_string)

# splitting the string using Strings.unicode_split method with "UFT-8" decoder 
Splited_string = tf.strings.unicode_split(Tensor_string2,"UTF-8")
print(Splited_string)
print(Splited_string[1])

# Encoding Decodings 
char = tf.ragged.constant([22,600])
encoded_str = tf.strings.unicode_encode(char, "UTF-8")
print(encoded_str)

decoded_str = tf.strings.unicode_decode(encoded_str,"UTF-8")
print(decoded_str)

tf.Tensor(b'hello', shape=(), dtype=string)
tf.Tensor(b'manish swami', shape=(), dtype=string)
tf.Tensor(b'hello manish swami', shape=(), dtype=string)
tf.Tensor([b'm' b'a' b'n' b'i' b's' b'h' b' ' b's' b'w' b'a' b'm' b'i'], shape=(12,), dtype=string)
tf.Tensor(b'a', shape=(), dtype=string)
tf.Tensor(b'\x16\xc9\x98', shape=(), dtype=string)
tf.Tensor([ 22 600], shape=(2,), dtype=int32)
